name: Make CMake (BSD)
run-name: Make CMake ${{ inputs.cmake_version }}
on:
  workflow_dispatch:
    inputs:
      cmake_version:
        description: "CMake Version"
        required: true
        default: "4.1.2"
      ninja_version:
        description: "Ninja Version"
        required: true
        default: "1.12.1"

permissions:
  contents: write
  packages: read

jobs:
  make:
    uses: ./.github/workflows/make-cmake.yml
    secrets: inherit
    with:
      platform: bsd
      cmake_version: ${{ inputs.cmake_version }}
      ninja_version: ${{ inputs.ninja_version }}
      # riscv32-netbsd-none, powerpc-netbsd-eabi, powerpc-freebsd-eabihf
      targets: >-
        ["aarch64-freebsd-none", "aarch64-netbsd-none", "aarch64-openbsd-none",
         "aarch64_be-netbsd-none", "arm-freebsd-eabihf", "arm-netbsd-eabi",
         "arm-netbsd-eabihf", "armeb-netbsd-eabi", "armeb-netbsd-eabihf",
         "mips-netbsd-eabi", "mips-netbsd-eabihf", "mipsel-netbsd-eabi",
         "mipsel-netbsd-eabihf", "mips64el-openbsd-none", "mips64-openbsd-none",
         "powerpc-netbsd-eabihf", "powerpc64-freebsd-none",
         "powerpc64le-freebsd-none", "riscv64-freebsd-none", "x86-freebsd-none",
         "x86-netbsd-none", "x86_64-freebsd-none", "x86_64-netbsd-none",
         "arm-openbsd-eabi", "powerpc-openbsd-eabihf", "riscv64-openbsd-none",
         "x86-openbsd-none", "x86_64-openbsd-none"]
